### ISSUE TITLE
Are the scripts in this ZIP more up to date than what's in your YT video?

### ISSUE THREAD

**Issue by deejaykaytee** [rhedgeco/Synthic#1]
Hey Ryan! I'd like to create a unique step sequencer type program for mobile using Unity and I came across your YT video in my research.  Made me slow down a bit to learn more.  So, I been following along with your scripts open but noticing some things don't match up.  Like, the instance of StereoData in one of your scripts in the ZIP is not in your video.  So, I started updating things as I saw in the video and ended up with an error in my now botched SynthBuffer.cs file.  Just wondering if I should've just left the scripts as is, but thought I could be missing out on new code since I was finding missing pieces.  Let me know either way and I can't wait to see more videos!

Thanks,
Kris

**Comment by rhedgeco** [comment]
Hey! Sorry for not getting back. The code in the repo is the most up to date.
